name: deploy_to_firebase
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: GroceryApp
    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      with: 
        secrets: | 
           $FIREBASE_TOKEN
      
